/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.ide;


/**
 * Use this class to register ide components.
 */
public class TraceryLanguageIdeModule extends AbstractTraceryLanguageIdeModule {
}
