/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.languages.tracery.ui.internal.TraceryActivator;

public class TraceryLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TraceryActivator.getInstance().getInjector("uk.ac.kcl.inf.languages.tracery.TraceryLanguage");
	}

}
