/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import uk.ac.kcl.inf.languages.tracery.services.TraceryLanguageGrammarAccess;

@SuppressWarnings("all")
public class TraceryLanguageSyntacticSequencer extends AbstractSyntacticSequencer {

	protected TraceryLanguageGrammarAccess grammarAccess;
	protected AbstractElementAlias match_InnerStatement_NumberSignKeyword_1_0_or_NumberSignKeyword_2_0_or_NumberSignKeyword_3_0_or_NumberSignKeyword_4_0_or_NumberSignKeyword_5_0;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (TraceryLanguageGrammarAccess) access;
		match_InnerStatement_NumberSignKeyword_1_0_or_NumberSignKeyword_2_0_or_NumberSignKeyword_3_0_or_NumberSignKeyword_4_0_or_NumberSignKeyword_5_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getInnerStatementAccess().getNumberSignKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getInnerStatementAccess().getNumberSignKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getInnerStatementAccess().getNumberSignKeyword_3_0()), new TokenAlias(false, false, grammarAccess.getInnerStatementAccess().getNumberSignKeyword_4_0()), new TokenAlias(false, false, grammarAccess.getInnerStatementAccess().getNumberSignKeyword_5_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_InnerStatement_NumberSignKeyword_1_0_or_NumberSignKeyword_2_0_or_NumberSignKeyword_3_0_or_NumberSignKeyword_4_0_or_NumberSignKeyword_5_0.equals(syntax))
				emit_InnerStatement_NumberSignKeyword_1_0_or_NumberSignKeyword_2_0_or_NumberSignKeyword_3_0_or_NumberSignKeyword_4_0_or_NumberSignKeyword_5_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '#' | '#' | '#' | '#' | '#'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) name=ID
	 */
	protected void emit_InnerStatement_NumberSignKeyword_1_0_or_NumberSignKeyword_2_0_or_NumberSignKeyword_3_0_or_NumberSignKeyword_4_0_or_NumberSignKeyword_5_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
