/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TraceryLanguageUiModule extends AbstractTraceryLanguageUiModule {

	public TraceryLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
