/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.languages.tracery.ui.internal.TraceryActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TraceryLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TraceryActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TraceryActivator activator = TraceryActivator.getInstance();
		return activator != null ? activator.getInjector(TraceryActivator.UK_AC_KCL_INF_LANGUAGES_TRACERY_TRACERYLANGUAGE) : null;
	}

}
