/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.validation

import org.eclipse.xtext.validation.Check
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryLanguagePackage
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONLines
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StartValueImpl

/** 
 * This class contains custom validation rules. 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class TraceryLanguageValidator extends AbstractTraceryLanguageValidator { //	public static final String INVALID_NAME = "invalidName";
	//
	// @Check
	// public void checkGreetingStartsWithCapital(Greeting greeting) {
	// if (!Character.isUpperCase(greeting.getName().charAt(0))) {
	// warning("Name should start with a capital",
	// TraceryLanguagePackage.Literals.GREETING__NAME,
	// INVALID_NAME);
	// }
	// }
	
	public static val INVALID_VALUES_NUMBERS = 'uk.ac.kcl.inf.languages.tracery.INVALID_VALUES_NUMBERS'
	public static val INVALID_VARIABLE_NAME = 'uk.ac.kcl.inf.szschaler.turtles.INVALID_VARIABLE_NAME'
	
	@Check
	def lmao(InitialJSONLines initialJSONLine){
		
		if (!Character.isLowerCase(initialJSONLine.name.charAt(0))) {
			warning('Name should start with a lower-case character', initialJSONLine,
				TraceryLanguagePackage.Literals.INITIAL_JSON_LINES__VALUE, INVALID_VARIABLE_NAME)
		}
		
	}
		
	@Check
	def checkValuesDeclerationHasMoreThanOneValue(InitialJSONLines initialJSONLine){

		val value = initialJSONLine.value as StartValueImpl
 		
 		
	
		if(value.vals.size==0){
			warning("You have not declared any other possible forms of the sentence. Your output sentence may be very simple.",
			initialJSONLine,
			TraceryLanguagePackage.Literals.INITIAL_JSON_LINES__VALUE,
			INVALID_VALUES_NUMBERS)
		}

		
	}
}
