/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.scoping;

import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.DeclaredVariable;

/**
 * This class contains custom scoping description.
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class TraceryLanguageScopeProvider extends AbstractDeclarativeScopeProvider {
  public IScope scope_DeclaredVariable_variable(final DeclaredVariable context, final EReference ref) {
    return null;
  }
}
