/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.traceryLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inner Values</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryLanguagePackage#getInnerValues()
 * @model
 * @generated
 */
public interface InnerValues extends InitialJSONEnding
{
} // InnerValues
