/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.traceryLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.Statement#getInitialStatement <em>Initial Statement</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.Statement#getFinalStatement <em>Final Statement</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryLanguagePackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Initial Statement</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONLines}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initial Statement</em>' containment reference list.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryLanguagePackage#getStatement_InitialStatement()
   * @model containment="true"
   * @generated
   */
  EList<InitialJSONLines> getInitialStatement();

  /**
   * Returns the value of the '<em><b>Final Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Final Statement</em>' containment reference.
   * @see #setFinalStatement(FinalJSONLine)
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryLanguagePackage#getStatement_FinalStatement()
   * @model containment="true"
   * @generated
   */
  FinalJSONLine getFinalStatement();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.Statement#getFinalStatement <em>Final Statement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Final Statement</em>' containment reference.
   * @see #getFinalStatement()
   * @generated
   */
  void setFinalStatement(FinalJSONLine value);

} // Statement
