/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.traceryLanguage;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryLanguagePackage
 * @generated
 */
public interface TraceryLanguageFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TraceryLanguageFactory eINSTANCE = uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguageFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Tracery Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tracery Program</em>'.
   * @generated
   */
  TraceryProgram createTraceryProgram();

  /**
   * Returns a new object of class '<em>Initial JSON Line</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial JSON Line</em>'.
   * @generated
   */
  InitialJSONLine createInitialJSONLine();

  /**
   * Returns a new object of class '<em>Initial JSON Ending</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial JSON Ending</em>'.
   * @generated
   */
  InitialJSONEnding createInitialJSONEnding();

  /**
   * Returns a new object of class '<em>Start Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Start Value</em>'.
   * @generated
   */
  StartValue createStartValue();

  /**
   * Returns a new object of class '<em>Normal Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Normal Value</em>'.
   * @generated
   */
  NormalValue createNormalValue();

  /**
   * Returns a new object of class '<em>Inner Statements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inner Statements</em>'.
   * @generated
   */
  InnerStatements createInnerStatements();

  /**
   * Returns a new object of class '<em>Declared Variable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declared Variable</em>'.
   * @generated
   */
  DeclaredVariable createDeclaredVariable();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  TraceryLanguagePackage getTraceryLanguagePackage();

} //TraceryLanguageFactory
