/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.traceryLanguage;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryLanguagePackage
 * @generated
 */
public interface TraceryLanguageFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TraceryLanguageFactory eINSTANCE = uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguageFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Tracery Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tracery Program</em>'.
   * @generated
   */
  TraceryProgram createTraceryProgram();

  /**
   * Returns a new object of class '<em>Variable Decleration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable Decleration</em>'.
   * @generated
   */
  VariableDecleration createVariableDecleration();

  /**
   * Returns a new object of class '<em>Initial JSON Line</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial JSON Line</em>'.
   * @generated
   */
  InitialJSONLine createInitialJSONLine();

  /**
   * Returns a new object of class '<em>Normal JSON Line</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Normal JSON Line</em>'.
   * @generated
   */
  NormalJSONLine createNormalJSONLine();

  /**
   * Returns a new object of class '<em>start Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>start Value</em>'.
   * @generated
   */
  startValue createstartValue();

  /**
   * Returns a new object of class '<em>normal Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>normal Value</em>'.
   * @generated
   */
  normalValue createnormalValue();

  /**
   * Returns a new object of class '<em>Inner Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inner Statement</em>'.
   * @generated
   */
  InnerStatement createInnerStatement();

  /**
   * Returns a new object of class '<em>Starting JSON Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Starting JSON Expression</em>'.
   * @generated
   */
  StartingJSONExpression createStartingJSONExpression();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  TraceryLanguagePackage getTraceryLanguagePackage();

} //TraceryLanguageFactory
