/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.traceryLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface TraceryLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "traceryLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/languages/tracery/TraceryLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "traceryLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TraceryLanguagePackage eINSTANCE = uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryProgramImpl <em>Tracery Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryProgramImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getTraceryProgram()
   * @generated
   */
  int TRACERY_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACERY_PROGRAM__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Tracery Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACERY_PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StatementImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The feature id for the '<em><b>Initial Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__INITIAL_STATEMENT = 0;

  /**
   * The feature id for the '<em><b>Final Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__FINAL_STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialJSONLinesImpl <em>Initial JSON Lines</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialJSONLinesImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInitialJSONLines()
   * @generated
   */
  int INITIAL_JSON_LINES = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_JSON_LINES__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_JSON_LINES__VALUE = 1;

  /**
   * The number of structural features of the '<em>Initial JSON Lines</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_JSON_LINES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.FinalJSONLineImpl <em>Final JSON Line</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.FinalJSONLineImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getFinalJSONLine()
   * @generated
   */
  int FINAL_JSON_LINE = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL_JSON_LINE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Final JSON Line</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL_JSON_LINE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialJSONEndingImpl <em>Initial JSON Ending</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialJSONEndingImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInitialJSONEnding()
   * @generated
   */
  int INITIAL_JSON_ENDING = 4;

  /**
   * The number of structural features of the '<em>Initial JSON Ending</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_JSON_ENDING_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InnerValuesImpl <em>Inner Values</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InnerValuesImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInnerValues()
   * @generated
   */
  int INNER_VALUES = 5;

  /**
   * The number of structural features of the '<em>Inner Values</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INNER_VALUES_FEATURE_COUNT = INITIAL_JSON_ENDING_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.FinalJSONEndingImpl <em>Final JSON Ending</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.FinalJSONEndingImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getFinalJSONEnding()
   * @generated
   */
  int FINAL_JSON_ENDING = 6;

  /**
   * The number of structural features of the '<em>Final JSON Ending</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL_JSON_ENDING_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StartValueImpl <em>Start Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StartValueImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getStartValue()
   * @generated
   */
  int START_VALUE = 7;

  /**
   * The feature id for the '<em><b>Vals</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_VALUE__VALS = INNER_VALUES_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value Inner Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_VALUE__VALUE_INNER_STATEMENTS = INNER_VALUES_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Start Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_VALUE_FEATURE_COUNT = INNER_VALUES_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.NormalValueImpl <em>Normal Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.NormalValueImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getNormalValue()
   * @generated
   */
  int NORMAL_VALUE = 8;

  /**
   * The feature id for the '<em><b>Value Inner Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_VALUE__VALUE_INNER_STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Normal Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InnerStatementsImpl <em>Inner Statements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InnerStatementsImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInnerStatements()
   * @generated
   */
  int INNER_STATEMENTS = 9;

  /**
   * The number of structural features of the '<em>Inner Statements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INNER_STATEMENTS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StringDeclarationImpl <em>String Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StringDeclarationImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getStringDeclaration()
   * @generated
   */
  int STRING_DECLARATION = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_DECLARATION__VALUE = INNER_STATEMENTS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_DECLARATION_FEATURE_COUNT = INNER_STATEMENTS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.DeclaredVariableImpl <em>Declared Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.DeclaredVariableImpl
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getDeclaredVariable()
   * @generated
   */
  int DECLARED_VARIABLE = 11;

  /**
   * The feature id for the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARED_VARIABLE__VARIABLE = INNER_STATEMENTS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Declared Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARED_VARIABLE_FEATURE_COUNT = INNER_STATEMENTS_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryProgram <em>Tracery Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tracery Program</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryProgram
   * @generated
   */
  EClass getTraceryProgram();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryProgram#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryProgram#getStatements()
   * @see #getTraceryProgram()
   * @generated
   */
  EReference getTraceryProgram_Statements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.Statement#getInitialStatement <em>Initial Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Initial Statement</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.Statement#getInitialStatement()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_InitialStatement();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.Statement#getFinalStatement <em>Final Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Final Statement</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.Statement#getFinalStatement()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_FinalStatement();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONLines <em>Initial JSON Lines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initial JSON Lines</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONLines
   * @generated
   */
  EClass getInitialJSONLines();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONLines#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONLines#getName()
   * @see #getInitialJSONLines()
   * @generated
   */
  EAttribute getInitialJSONLines_Name();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONLines#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONLines#getValue()
   * @see #getInitialJSONLines()
   * @generated
   */
  EReference getInitialJSONLines_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.FinalJSONLine <em>Final JSON Line</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Final JSON Line</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.FinalJSONLine
   * @generated
   */
  EClass getFinalJSONLine();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.FinalJSONLine#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.FinalJSONLine#getValue()
   * @see #getFinalJSONLine()
   * @generated
   */
  EReference getFinalJSONLine_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONEnding <em>Initial JSON Ending</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initial JSON Ending</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InitialJSONEnding
   * @generated
   */
  EClass getInitialJSONEnding();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InnerValues <em>Inner Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inner Values</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InnerValues
   * @generated
   */
  EClass getInnerValues();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.FinalJSONEnding <em>Final JSON Ending</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Final JSON Ending</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.FinalJSONEnding
   * @generated
   */
  EClass getFinalJSONEnding();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.StartValue <em>Start Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Start Value</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.StartValue
   * @generated
   */
  EClass getStartValue();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.StartValue#getVals <em>Vals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vals</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.StartValue#getVals()
   * @see #getStartValue()
   * @generated
   */
  EReference getStartValue_Vals();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.StartValue#getValueInnerStatements <em>Value Inner Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Value Inner Statements</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.StartValue#getValueInnerStatements()
   * @see #getStartValue()
   * @generated
   */
  EReference getStartValue_ValueInnerStatements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.NormalValue <em>Normal Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Normal Value</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.NormalValue
   * @generated
   */
  EClass getNormalValue();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.NormalValue#getValueInnerStatements <em>Value Inner Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Value Inner Statements</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.NormalValue#getValueInnerStatements()
   * @see #getNormalValue()
   * @generated
   */
  EReference getNormalValue_ValueInnerStatements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.InnerStatements <em>Inner Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inner Statements</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.InnerStatements
   * @generated
   */
  EClass getInnerStatements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.StringDeclaration <em>String Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Declaration</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.StringDeclaration
   * @generated
   */
  EClass getStringDeclaration();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.StringDeclaration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.StringDeclaration#getValue()
   * @see #getStringDeclaration()
   * @generated
   */
  EAttribute getStringDeclaration_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.DeclaredVariable <em>Declared Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declared Variable</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.DeclaredVariable
   * @generated
   */
  EClass getDeclaredVariable();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.DeclaredVariable#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable</em>'.
   * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.DeclaredVariable#getVariable()
   * @see #getDeclaredVariable()
   * @generated
   */
  EReference getDeclaredVariable_Variable();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TraceryLanguageFactory getTraceryLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryProgramImpl <em>Tracery Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryProgramImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getTraceryProgram()
     * @generated
     */
    EClass TRACERY_PROGRAM = eINSTANCE.getTraceryProgram();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRACERY_PROGRAM__STATEMENTS = eINSTANCE.getTraceryProgram_Statements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StatementImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Initial Statement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__INITIAL_STATEMENT = eINSTANCE.getStatement_InitialStatement();

    /**
     * The meta object literal for the '<em><b>Final Statement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__FINAL_STATEMENT = eINSTANCE.getStatement_FinalStatement();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialJSONLinesImpl <em>Initial JSON Lines</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialJSONLinesImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInitialJSONLines()
     * @generated
     */
    EClass INITIAL_JSON_LINES = eINSTANCE.getInitialJSONLines();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INITIAL_JSON_LINES__NAME = eINSTANCE.getInitialJSONLines_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INITIAL_JSON_LINES__VALUE = eINSTANCE.getInitialJSONLines_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.FinalJSONLineImpl <em>Final JSON Line</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.FinalJSONLineImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getFinalJSONLine()
     * @generated
     */
    EClass FINAL_JSON_LINE = eINSTANCE.getFinalJSONLine();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FINAL_JSON_LINE__VALUE = eINSTANCE.getFinalJSONLine_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialJSONEndingImpl <em>Initial JSON Ending</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InitialJSONEndingImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInitialJSONEnding()
     * @generated
     */
    EClass INITIAL_JSON_ENDING = eINSTANCE.getInitialJSONEnding();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InnerValuesImpl <em>Inner Values</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InnerValuesImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInnerValues()
     * @generated
     */
    EClass INNER_VALUES = eINSTANCE.getInnerValues();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.FinalJSONEndingImpl <em>Final JSON Ending</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.FinalJSONEndingImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getFinalJSONEnding()
     * @generated
     */
    EClass FINAL_JSON_ENDING = eINSTANCE.getFinalJSONEnding();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StartValueImpl <em>Start Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StartValueImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getStartValue()
     * @generated
     */
    EClass START_VALUE = eINSTANCE.getStartValue();

    /**
     * The meta object literal for the '<em><b>Vals</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference START_VALUE__VALS = eINSTANCE.getStartValue_Vals();

    /**
     * The meta object literal for the '<em><b>Value Inner Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference START_VALUE__VALUE_INNER_STATEMENTS = eINSTANCE.getStartValue_ValueInnerStatements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.NormalValueImpl <em>Normal Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.NormalValueImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getNormalValue()
     * @generated
     */
    EClass NORMAL_VALUE = eINSTANCE.getNormalValue();

    /**
     * The meta object literal for the '<em><b>Value Inner Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NORMAL_VALUE__VALUE_INNER_STATEMENTS = eINSTANCE.getNormalValue_ValueInnerStatements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InnerStatementsImpl <em>Inner Statements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.InnerStatementsImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getInnerStatements()
     * @generated
     */
    EClass INNER_STATEMENTS = eINSTANCE.getInnerStatements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StringDeclarationImpl <em>String Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StringDeclarationImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getStringDeclaration()
     * @generated
     */
    EClass STRING_DECLARATION = eINSTANCE.getStringDeclaration();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_DECLARATION__VALUE = eINSTANCE.getStringDeclaration_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.DeclaredVariableImpl <em>Declared Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.DeclaredVariableImpl
     * @see uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.TraceryLanguagePackageImpl#getDeclaredVariable()
     * @generated
     */
    EClass DECLARED_VARIABLE = eINSTANCE.getDeclaredVariable();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARED_VARIABLE__VARIABLE = eINSTANCE.getDeclaredVariable_Variable();

  }

} //TraceryLanguagePackage
