/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import uk.ac.kcl.inf.languages.tracery.traceryLanguage.InnerValues;
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Inner Values</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InnerValuesImpl extends InitialJSONEndingImpl implements InnerValues
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InnerValuesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TraceryLanguagePackage.Literals.INNER_VALUES;
  }

} //InnerValuesImpl
