/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uk.ac.kcl.inf.languages.tracery.traceryLanguage.StartingJSONExpression;
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryLanguagePackage;
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.VariableDecleration;
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.normalValue;
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.startValue;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Starting JSON Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StartingJSONExpressionImpl#getStartVal <em>Start Val</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StartingJSONExpressionImpl#getVals <em>Vals</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StartingJSONExpressionImpl#getVar <em>Var</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StartingJSONExpressionImpl extends StatementImpl implements StartingJSONExpression
{
  /**
   * The cached value of the '{@link #getStartVal() <em>Start Val</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartVal()
   * @generated
   * @ordered
   */
  protected EList<startValue> startVal;

  /**
   * The cached value of the '{@link #getVals() <em>Vals</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVals()
   * @generated
   * @ordered
   */
  protected EList<normalValue> vals;

  /**
   * The cached value of the '{@link #getVar() <em>Var</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar()
   * @generated
   * @ordered
   */
  protected VariableDecleration var;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StartingJSONExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TraceryLanguagePackage.Literals.STARTING_JSON_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<startValue> getStartVal()
  {
    if (startVal == null)
    {
      startVal = new EObjectContainmentEList<startValue>(startValue.class, this, TraceryLanguagePackage.STARTING_JSON_EXPRESSION__START_VAL);
    }
    return startVal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<normalValue> getVals()
  {
    if (vals == null)
    {
      vals = new EObjectContainmentEList<normalValue>(normalValue.class, this, TraceryLanguagePackage.STARTING_JSON_EXPRESSION__VALS);
    }
    return vals;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableDecleration getVar()
  {
    if (var != null && var.eIsProxy())
    {
      InternalEObject oldVar = (InternalEObject)var;
      var = (VariableDecleration)eResolveProxy(oldVar);
      if (var != oldVar)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, TraceryLanguagePackage.STARTING_JSON_EXPRESSION__VAR, oldVar, var));
      }
    }
    return var;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VariableDecleration basicGetVar()
  {
    return var;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVar(VariableDecleration newVar)
  {
    VariableDecleration oldVar = var;
    var = newVar;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TraceryLanguagePackage.STARTING_JSON_EXPRESSION__VAR, oldVar, var));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.STARTING_JSON_EXPRESSION__START_VAL:
        return ((InternalEList<?>)getStartVal()).basicRemove(otherEnd, msgs);
      case TraceryLanguagePackage.STARTING_JSON_EXPRESSION__VALS:
        return ((InternalEList<?>)getVals()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.STARTING_JSON_EXPRESSION__START_VAL:
        return getStartVal();
      case TraceryLanguagePackage.STARTING_JSON_EXPRESSION__VALS:
        return getVals();
      case TraceryLanguagePackage.STARTING_JSON_EXPRESSION__VAR:
        if (resolve) return getVar();
        return basicGetVar();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.STARTING_JSON_EXPRESSION__START_VAL:
        getStartVal().clear();
        getStartVal().addAll((Collection<? extends startValue>)newValue);
        return;
      case TraceryLanguagePackage.STARTING_JSON_EXPRESSION__VALS:
        getVals().clear();
        getVals().addAll((Collection<? extends normalValue>)newValue);
        return;
      case TraceryLanguagePackage.STARTING_JSON_EXPRESSION__VAR:
        setVar((VariableDecleration)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.STARTING_JSON_EXPRESSION__START_VAL:
        getStartVal().clear();
        return;
      case TraceryLanguagePackage.STARTING_JSON_EXPRESSION__VALS:
        getVals().clear();
        return;
      case TraceryLanguagePackage.STARTING_JSON_EXPRESSION__VAR:
        setVar((VariableDecleration)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.STARTING_JSON_EXPRESSION__START_VAL:
        return startVal != null && !startVal.isEmpty();
      case TraceryLanguagePackage.STARTING_JSON_EXPRESSION__VALS:
        return vals != null && !vals.isEmpty();
      case TraceryLanguagePackage.STARTING_JSON_EXPRESSION__VAR:
        return var != null;
    }
    return super.eIsSet(featureID);
  }

} //StartingJSONExpressionImpl
