/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uk.ac.kcl.inf.languages.tracery.traceryLanguage.InnerStatements;
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.NormalValue;
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.StartValue;
import uk.ac.kcl.inf.languages.tracery.traceryLanguage.TraceryLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Start Value</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StartValueImpl#getVals <em>Vals</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.languages.tracery.traceryLanguage.impl.StartValueImpl#getValueInnerStatements <em>Value Inner Statements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StartValueImpl extends InnerValuesImpl implements StartValue
{
  /**
   * The cached value of the '{@link #getVals() <em>Vals</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVals()
   * @generated
   * @ordered
   */
  protected EList<NormalValue> vals;

  /**
   * The cached value of the '{@link #getValueInnerStatements() <em>Value Inner Statements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueInnerStatements()
   * @generated
   * @ordered
   */
  protected EList<InnerStatements> valueInnerStatements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StartValueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TraceryLanguagePackage.Literals.START_VALUE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<NormalValue> getVals()
  {
    if (vals == null)
    {
      vals = new EObjectContainmentEList<NormalValue>(NormalValue.class, this, TraceryLanguagePackage.START_VALUE__VALS);
    }
    return vals;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<InnerStatements> getValueInnerStatements()
  {
    if (valueInnerStatements == null)
    {
      valueInnerStatements = new EObjectContainmentEList<InnerStatements>(InnerStatements.class, this, TraceryLanguagePackage.START_VALUE__VALUE_INNER_STATEMENTS);
    }
    return valueInnerStatements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.START_VALUE__VALS:
        return ((InternalEList<?>)getVals()).basicRemove(otherEnd, msgs);
      case TraceryLanguagePackage.START_VALUE__VALUE_INNER_STATEMENTS:
        return ((InternalEList<?>)getValueInnerStatements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.START_VALUE__VALS:
        return getVals();
      case TraceryLanguagePackage.START_VALUE__VALUE_INNER_STATEMENTS:
        return getValueInnerStatements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.START_VALUE__VALS:
        getVals().clear();
        getVals().addAll((Collection<? extends NormalValue>)newValue);
        return;
      case TraceryLanguagePackage.START_VALUE__VALUE_INNER_STATEMENTS:
        getValueInnerStatements().clear();
        getValueInnerStatements().addAll((Collection<? extends InnerStatements>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.START_VALUE__VALS:
        getVals().clear();
        return;
      case TraceryLanguagePackage.START_VALUE__VALUE_INNER_STATEMENTS:
        getValueInnerStatements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TraceryLanguagePackage.START_VALUE__VALS:
        return vals != null && !vals.isEmpty();
      case TraceryLanguagePackage.START_VALUE__VALUE_INNER_STATEMENTS:
        return valueInnerStatements != null && !valueInnerStatements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //StartValueImpl
